# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GapsFiller
                                 A QGIS plugin
 This plugin fills the gaps in hyperspectral photos to make an ortophoto
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-02
        copyright            : (C) 2026 by Duke
        email                : st087204@student.spbu.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GapsFiller class from file GapsFiller.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gaps_filler import GapsFiller
    return GapsFiller(iface)
